


[local]
import_source = "rhythmbox"
# playlists will be created here
local_music_dir = "/home/andrew/Music/library"

[transfer]
method = "adb"
va_dir = "VA"                                    # directory to put files that are reside outside of the music library dir
playlist_format = "m3u"
device_music_dir = "/storage/self/primary/Music"

[adb]
command = "adb -d push --sync \"<source_file>\" \"<base>/<dest_file>\""


